# Generated by Django 5.2.6 on 2025-11-02 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(db_index=True, max_length=64, unique=True)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('parent_item_category', models.CharField(blank=True, max_length=128)),
                ('base_unit_of_measure', models.CharField(blank=True, max_length=32)),
                ('item_category_code', models.CharField(blank=True, max_length=64)),
                ('type', models.CharField(blank=True, max_length=64)),
                ('length', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('width', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('height', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('volumetric_weight', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('material', models.CharField(blank=True, max_length=128)),
                ('hs_code', models.CharField(blank=True, max_length=32)),
                ('additional_measurement', models.CharField(blank=True, max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
