# Generated by Django 5.2.6 on 2025-11-15 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_area', '0003_forwarder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forwarder',
            name='vat_registration_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
