# Generated by Django 5.2.9 on 2026-03-08 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_area', '0004_alter_forwarder_vat_registration_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryEmailConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('email_to', models.TextField(help_text='Enter email addresses separated by commas')),
                ('cc', models.TextField(blank=True, help_text='Optional CC emails separated by commas', null=True)),
                ('bcc', models.TextField(blank=True, help_text='Optional BCC emails separated by commas', null=True)),
                ('email_text', models.TextField(help_text='Email message template')),
                ('is_active', models.BooleanField(default=True, help_text='Turn ON/OFF email sending')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
