# Generated by Django 5.2.9 on 2026-03-08 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_area', '0005_deliveryemailconfiguration'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deliveryemailconfiguration',
            options={'ordering': ['-created_at'], 'verbose_name': 'Delivery Email Configuration', 'verbose_name_plural': 'Delivery Email Configurations'},
        ),
        migrations.AddField(
            model_name='deliveryemailconfiguration',
            name='email_subject',
            field=models.CharField(blank=True, help_text='Email subject line', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='deliveryemailconfiguration',
            name='description',
            field=models.CharField(help_text='Internal name for this email configuration', max_length=255),
        ),
    ]
