# Generated by Django 5.2.6 on 2025-09-15 17:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pallet_number', models.CharField(max_length=50)),
                ('length_cm', models.DecimalField(decimal_places=2, max_digits=10)),
                ('width_cm', models.DecimalField(decimal_places=2, max_digits=10)),
                ('height_cm', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gross_weight_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('export', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pallets', to='core.export')),
            ],
        ),
    ]
