# Generated by Django 5.2.6 on 2025-09-26 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_pallet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lineitem',
            name='carbon_qty',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=12, null=True),
        ),
    ]
