# Generated by Django 5.2.6 on 2025-10-07 16:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_lineitem_carbon_qty'),
    ]

    operations = [
        migrations.AddField(
            model_name='export',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exports_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='export',
            name='declaration_a_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='export',
            name='declaration_c_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='export',
            name='declaration_register_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
