# Generated by Django 5.2.9 on 2025-12-31 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_export_created_by_export_declaration_a_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('warehouse', 'Warehouse'), ('logistic', 'Logistic'), ('employee', 'Other Employee'), ('planning', 'Planning'), ('finance', 'Finance')], default='employee', max_length=20),
        ),
    ]
