# Generated by Django 5.2.9 on 2026-02-28 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('warehouse', 'Warehouse'), ('logistic', 'Logistic'), ('procurement', 'Procurement'), ('employee', 'Other Employee'), ('planning', 'Planning'), ('finance', 'Finance')], default='employee', max_length=20),
        ),
    ]
