# Generated by Django 5.2.9 on 2026-03-26 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_user_two_factor_backup_codes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='two_factor_backup_codes',
        ),
    ]
