# Generated by Django 5.2.6 on 2025-11-12 16:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Import',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('import_code', models.CharField(editable=False, max_length=20, unique=True)),
                ('vendor_name', models.CharField(max_length=255)),
                ('exporter_country', models.CharField(blank=True, max_length=100, null=True)),
                ('incoterms', models.CharField(blank=True, max_length=20, null=True)),
                ('currency_code', models.CharField(blank=True, max_length=10, null=True)),
                ('goods_price', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('tracking_no', models.CharField(blank=True, max_length=100, null=True)),
                ('shipping_method', models.CharField(blank=True, max_length=20, null=True)),
                ('shipment_status', models.CharField(blank=True, max_length=20, null=True)),
                ('pickup_address', models.TextField(blank=True, null=True)),
                ('is_danger', models.BooleanField(default=False)),
                ('is_stackable', models.BooleanField(default=True)),
                ('expected_receipt_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='ImportSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('counter', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='NewImportLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'imports_newimportline',
            },
        ),
    ]
