# Generated by Django 5.2.6 on 2025-11-12 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imports', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NewImportLine',
        ),
        migrations.AddField(
            model_name='import',
            name='declaration_a_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='import',
            name='declaration_c_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='import',
            name='declaration_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
