# Generated by Django 5.2.6 on 2025-11-12 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imports', '0002_delete_newimportline_import_declaration_a_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='import',
            name='tracking_no',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
