# Generated by Django 5.2.6 on 2025-11-15 18:19

import django.db.models.deletion
import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_area', '0004_alter_forwarder_vat_registration_no'),
        ('imports', '0003_alter_import_tracking_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='import',
            name='forwarder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imports', to='admin_area.forwarder'),
        ),
        migrations.AlterField(
            model_name='import',
            name='exporter_country',
            field=django_countries.fields.CountryField(blank=True, max_length=2, null=True),
        ),
    ]
