# Generated by Django 5.2.6 on 2025-11-16 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imports', '0004_import_forwarder_alter_import_exporter_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='import',
            name='forwarder_reference',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='import',
            name='vendor_reference',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
