# Generated by Django 5.2.6 on 2025-11-22 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imports', '0005_import_forwarder_reference_import_vendor_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='import',
            name='total_gross_weight_kg',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='import',
            name='total_volumetric_weight_kg',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True),
        ),
    ]
