# Generated by Django 5.2.6 on 2025-11-22 17:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imports', '0006_import_total_gross_weight_kg_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_no', models.CharField(blank=True, max_length=100, null=True)),
                ('line_no', models.CharField(blank=True, max_length=50, null=True)),
                ('item_no', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('quantity', models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True)),
                ('unit_of_measure', models.CharField(blank=True, max_length=50, null=True)),
                ('unit_cost', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('line_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('expected_receipt_date', models.DateField(blank=True, null=True)),
                ('delivery_date', models.DateField(blank=True, null=True)),
                ('import_header', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='imports.import')),
            ],
        ),
    ]
