# Generated by Django 5.2.6 on 2025-11-23 18:40

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imports', '0007_importline'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_type', models.CharField(blank=True, choices=[('BOX', 'Box'), ('PALLET', 'Pallet'), ('SKID', 'Skid'), ('ROLL', 'Roll'), ('ENVELOPE', 'Envelope')], max_length=20, null=True)),
                ('length_cm', models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True)),
                ('width_cm', models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True)),
                ('height_cm', models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True)),
                ('gross_weight_kg', models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True)),
                ('unit_system', models.CharField(choices=[('metric', 'Metric (cm/kg)'), ('imperial', 'Imperial (in/lbs)')], default='metric', max_length=10)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('import_header', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='imports.import')),
            ],
        ),
    ]
