# Generated by Django 5.2.6 on 2025-12-07 17:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_area', '0004_alter_forwarder_vat_registration_no'),
        ('imports', '0009_import_brokerage_currency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='import',
            name='brokerage_forwarder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='brokerage_imports', to='admin_area.forwarder'),
        ),
        migrations.AddField(
            model_name='import',
            name='internal_delivery_forwarder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='internal_delivery_imports', to='admin_area.forwarder'),
        ),
        migrations.AddField(
            model_name='import',
            name='other1_forwarder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='other1_imports', to='admin_area.forwarder'),
        ),
        migrations.AddField(
            model_name='import',
            name='other2_forwarder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='other2_imports', to='admin_area.forwarder'),
        ),
        migrations.AddField(
            model_name='import',
            name='transport_forwarder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transport_imports', to='admin_area.forwarder'),
        ),
    ]
